### ISSUE TITLE
how can I mix swipe gesture and custom activity transition?

### ISSUE THREAD

**Issue by AhmadVatani** [codepath/android-animation-gestures-demo#3]
I want to create a swipe gesture for back to previous activity. i want to create it with transition and animation. what should i do?
tnx

**Comment by nesquena** [comment]
Easiest bet are these libraries:
- https://github.com/ikew0ng/SwipeBackLayout
- https://github.com/sockeqwe/SwipeBack

**Comment by AhmadVatani** [comment]
tnx nesquena :)
